# values.yaml
redis:
  image:
    registry: docker.io
    repository: bitnamilegacy/redis
    tag: 8.2.1-debian-12-r0
  
  auth:
    enabled: true
    password: "Qhfhfh12#"

  master:
    persistence:
      enabled: true  # 데이터를 저장하기 위해 true로 변경
      size: 8Gi      # 적절한 용량 설정
      storageClass: "local-path" # 우리가 앞서 설치한 SC 이름 지정

  replica:
    replicaCount: 1
    persistence:
      enabled: true
      size: 8Gi
      storageClass: "local-path"
