apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-first-gitops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sophying/GitOps.git
    targetRevision: HEAD
    path: .  # Chart.yaml이 있는 현재 폴더
    # 아래 helm 섹션을 명확히 정의함으로써 'DIRECTORY' 인식을 강제로 차단합니다.
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: redis-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
