apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-first-gitops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sophying/GitOps.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: redis-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
